### ISSUE TITLE
something wrong when I used  pcl::OpenNIGrabber().

### ISSUE THREAD

**Issue by yrd241** [percipioxyz/camport_openni2#1]
Hi

I installed the OpenNI packages in ubuntu 14.04 followed the step you post.

but the below problem occured when I called the pcl::OpenNIGrabber().

` /usr/include/boost/smart_ptr/shared_ptr.hpp:646: typename boost::detail::sp_dereference<T>::type boost::shared_ptr<T>::operator*() const [with T = pcl::Grabber; typename boost::detail::sp_dereference<T>::type = pcl::Grabber&]: Assertion `px != 0' failed.`

Does Percipio can not support the OpenNIGrabber in pcl ?   I'm sure my system has installed the OpenNI2-support as another OpenNI device could be opened.

**Comment by percipioxyz** [comment]
are you using this camport_openni2 code?

**Comment by percipioxyz** [comment]
could you please share your test code?

**Comment by yrd241** [comment]
OK.  Here is my test code:

`#include <pcl/io/openni_grabber.h>
#include <iostream>

int main(){
  boost::shared_ptr<pcl::Grabber> capture;
  capture.reset(new pcl::openni_grabber());
  return 0;
}`

And when I call the pcl::openni_grabber( )  the error would be occurred like I said before.

**Comment by yrd241** [comment]
OK. Here is my test code:

`#include <pcl/io/openni_grabber.h>
#include <iostream>
int main(){
       boost::shared_ptrpcl::Grabber capture;
       capture.reset(new pcl::openni_grabber());
       return 0;
}`

And when I call the pcl::openni_grabber( ) the error would be occurred like I said before.

**Comment by percipioxyz** [comment]
cannot reproduce this issue with your code，test this code with asus xtion pro, and get following error. could you please tell us your detailed reproduce steps and the ENV infomation，the version number of openni，PCL，and etc. Thanks.

main.cpp

 #include <pcl/io/openni_grabber.h>
int main()
{
    boost::shared_ptr<pcl::Grabber> capture;
    capture.reset(new pcl::OpenNIGrabber());
    return 0;
}

g++ main.cpp -I/usr/include/pcl-1.7 -I/usr/include/eigen3 -I/usr/include/ni -lpcl_io -lpcl_common -lboost_system -lOpenNI
qxji@qxji-desktop:~/tmp$ ./a.out
terminate called after throwing an instance of 'pcl::IOException'
  what():  void pcl::OpenNIGrabber::setupDevice(const string&, const pcl::OpenNIGrabber::Mode&, const pcl::OpenNIGrabber::Mode&) in /build/pcl-1.7-K_Z193/pcl-1.7-1.7.1/io/src/openni_grabber.cpp @ 373 : No matching device found. openni_wrapper::OpenNIDevice::OpenNIDevice(xn::Context&, const xn::NodeInfo&, const xn::NodeInfo&, const xn::NodeInfo&, const xn::NodeInfo&) @ /build/pcl-1.7-K_Z193/pcl-1.7-1.7.1/io/src/openni_camera/openni_device.cpp @ 129 : creating depth generator failed. Reason: USB interface is not supported!
Aborted (core dumped)

**Comment by yrd241** [comment]
appreciate for your response :)
This is my screenshot of test code in the QTCreator.
![image](https://cloud.githubusercontent.com/assets/5702651/17685937/ef1299ce-639a-11e6-94ec-d70793f5aa50.png)
and the screenshot  of pro. file of  the QT project.
![image](https://cloud.githubusercontent.com/assets/5702651/17686075/07efd9a6-639c-11e6-9d85-f9546d742314.png)

see , My output is  ok , when I used Asus Xtion Pro.
![image](https://cloud.githubusercontent.com/assets/5702651/17686161/c4baf76e-639c-11e6-8faa-a6c18a18efe4.png)

I have pcl 1.8  and openni 2.x . 

I think the "USB interface is not supported!" error maybe you would "sudo apt-get install --reinstall libopenni-sensor-primesense0 "  based on http://answers.ros.org/question/109411/asus-xtion-problems-with-ubuntu-1204-running-ros-fuerte/

**Comment by percipioxyz** [comment]
Considering our depth sensor only support OpenNI2 driver now, but in our qt pro, seems you linked the -lOpenNI -lOpenNI2.
I guess your test case is linking the OpenNI lib, not OpenNI2, while xtion support both of them. 

Could you find your pcl include path, is there a header file "openni2_grabber.h"? Seems it a new feature in any branch of pcl,
https://github.com/PointCloudLibrary/pcl/commit/0b8856784337e478e51e7237acf22539ff7ebb23

I tried to only link -lOpenNI2, but it failed at linking stage. Could you try to run "ldd main.out" to see if it linked the OpenNI2?

**Comment by yrd241** [comment]
OK. I run "ldd main.out" ,and found both OpenNi and OpenNI2 all be linked .

![image](https://cloud.githubusercontent.com/assets/5702651/17688862/ac9e3df8-63b5-11e6-90f5-cb6e0e6dfb65.png) 

Considering the your camera just support OpenNI2 , I modified the codes like below:
#include <pcl/io/openni2_grabber.h>
#include <iostream>

int main()
{
    boost::shared_ptr<pcl::Grabber> capture;
    pcl::io::OpenNI2Grabber *interface = new pcl::io::OpenNI2Grabber();
    capture.reset(interface);
    if(interface!=NULL)
        std::cout<<"ok"<<std::endl;
    std::cin.ignore();
    return 0;
}
 
and only linked  -lOpenNi2.
But when I run the binary with  percipioxyz camera  , get the following errors:

![image](https://cloud.githubusercontent.com/assets/5702651/17689026/05f81350-63b7-11e6-94d6-82deae20e914.png)

Is  there something wrong in my codes to use OpenNI2Grabber ?

**Comment by percipioxyz** [comment]
the exception in this log shows that the PCL library needs the the IR stream data interface, the latest commit can fix this issue, have a try please.

**Comment by percipioxyz** [comment]
Have you tested the latest code?

**Comment by yrd241** [comment]
so sorry , very busy recently. 

Cool , It works by using the latest code.

Thank you very much.

However, I found  a  strange problem. Just when I get the XYZ clouds as using 
`boost::function<void(const pcl::PointCloud<PointXYZ>::ConstPtr&)> f = boost::bind (&myClass::myFun, this, _1);`

`interface->registerCallback (f);` 
directly.

then  I observed My clouds data were very weird .. 

Looks like all points came from a same flat plane , and in any case  I wheeled the viewer , objects all be flat .

![image](https://cloud.githubusercontent.com/assets/5702651/18007870/58b84f82-6bd8-11e6-9148-49f016fffddf.png)

Does it  support reading the xyz clouds using openNI2 interface directly ?

**Comment by percipioxyz** [comment]
OpenNI2 only support three type of stream, Depth, IR and RGB. It doesn't upload point cloud directly.
All point cloud is calculated based on depth and camera intrinsic parameter.
you may want to check the correctness of depth which got from OpenNI2Grabber.

**Comment by yrd241** [comment]
Ok . I got that.
Thanks a loooot !!

**Comment by niranjanreddy891** [comment]
@yrd241 and @percipioxyz , i am facing almost similar issue.
![This is the screenshot of my error](https://user-images.githubusercontent.com/33854825/36967813-ca6724be-2086-11e8-8f78-0f90cdf5d866.png).

I am using Visual Studio-2013 on win-7 64bit version.

**Comment by yrd241** [comment]
Did you use the release of PCL that support the openni2 or include the header file "pcl/io/openni2_grabber.h" @niranjanreddy891

**Comment by niranjanreddy891** [comment]
yes I did include that header file in my code. Also I used PCL all-in-one installer from here [http://unanancyowen.com/en/pcl18/](url). openNI2 came along with that. Please help me in this issue

**Comment by bartfj** [comment]
@niranjanreddy891 , obviously,  your sample code couldn't found definition of Openno2_Grabber in PCL installed on your pc, please make sure openni2_grabber.h is exist, or the include path is right, or others

**Comment by kingguardian2526** [comment]
![image](https://user-images.githubusercontent.com/37320847/38190161-4342054a-368d-11e8-92bf-50fb19d7dcca.png)
@yrd241 @percipioxyz @niranjanreddy891  why I always meet this error when using openni2_grabber. Please help me

**Comment by hausfrau87** [comment]
@kingguardian2526: this is a sign that your kinect is not getting recognized properly. I solved this by building a kinect2.dll by compiling https://github.com/occipital/OpenNI2/tree/kinect2 and then putting this in my binaries folder.

**Comment by CesMak** [comment]
Hey there,
I have a similar issue. I would like to use openni2 at least my openni2 ros package is working. However 
I would like to get this code to run:

http://pointclouds.org/documentation/tutorials/tracking.php

with my asus xtion pro camera. Unfortunately the code just has this include:

#include <pcl/io/openni_grabber.h>

so i changed it to

#include <pcl/io/openni2_grabber.h>

and got this error:

fatal error: pcl/io/openni2_grabber.h: No such file or directory
 #include <pcl/io/openni2_grabber.h>

do I somehow have to link to openni2? or just need another pcl version?

Here is my cmake lists:
cmake_minimum_required(VERSION 2.8 FATAL_ERROR)

project(openni_tracking)

find_package(PCL 1.7 REQUIRED)

include_directories(${PCL_INCLUDE_DIRS}
)

link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})

add_executable (tracking_sample tracking_sample.cpp)
target_link_libraries (tracking_sample ${PCL_LIBRARIES})

**Comment by CesMak** [comment]
Guess my problem is that I need the new 1.8 version of pcl or may it be enough to just get the newest version of

libpcl_io:
