### ISSUE TITLE
使用新版libcamm.so错误

### ISSUE THREAD

**Issue by woshidag** [percipioxyz/camport_openni2#2]
使用最新的libcamm.so 运行./SimpleRead_x64会出现一下错误信息：
PercipioDepthSensor::streamGetNextFrame, Failed in FramePackageGet()
关闭程序后，设备上的蓝灯会长亮

使用之前（指的是release前版本）的libcamm.so则正常。rviz里也可以看到图像。

**Comment by percipioxyz** [comment]
是今天下载的吗，请提供代码commit号，以便追查。

**Comment by woshidag** [comment]
什么是commit号

**Comment by percipioxyz** [comment]
commit号是指代码提交到github仓库时生成的这个提交记录，即commit log。

你使用的代码是哪个版本，提交记录中的最后一次提交时什么时间？

**Comment by woshidag** [comment]
camport_linux的 5e79b2a

**Comment by percipioxyz** [comment]
已添加针对这个问题的修改，请更新实验，谢谢

**Comment by percipioxyz** [comment]
新版本是否已经解决问题？

**Comment by woshidag** [comment]
已经解决
